// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: SWYP-Find/design-tokens repo (primitive.json / semantic.json / component.json)

import SwiftUI

public extension ShapeStyle where Self == Color {

  // MARK: - Primitive / Primary
  static var primary50: Color { .init(hex: "F3EBE9") }
  static var primary100: Color { .init(hex: "E7D7D3") }
  static var primary200: Color { .init(hex: "D0AFA8") }
  static var primary300: Color { .init(hex: "B8887C") }
  static var primary400: Color { .init(hex: "A16051") }
  static var primary500: Color { .init(hex: "893825") }
  static var primary600: Color { .init(hex: "7A3626") }
  static var primary700: Color { .init(hex: "71372A") }
  static var primary800: Color { .init(hex: "653226") }
  static var primary900: Color { .init(hex: "4E2A21") }

  // MARK: - Primitive / Secondary
  static var secondary50: Color { .init(hex: "FCF8F1") }
  static var secondary100: Color { .init(hex: "F9F1E3") }
  static var secondary200: Color { .init(hex: "F3E3C7") }
  static var secondary300: Color { .init(hex: "EDD5AC") }
  static var secondary400: Color { .init(hex: "E7C790") }
  static var secondary500: Color { .init(hex: "E1B974") }
  static var secondary600: Color { .init(hex: "CEA969") }
  static var secondary700: Color { .init(hex: "B7965C") }
  static var secondary800: Color { .init(hex: "A38653") }
  static var secondary900: Color { .init(hex: "92784A") }

  // MARK: - Primitive / Beige
  static var beige50: Color { .init(hex: "FEFEFD") }
  static var beige100: Color { .init(hex: "FDFCFB") }
  static var beige200: Color { .init(hex: "FBF9F7") }
  static var beige300: Color { .init(hex: "F9F7F2") }
  static var beige400: Color { .init(hex: "F7F4EE") }
  static var beige500: Color { .init(hex: "F5F1EA") }
  static var beige600: Color { .init(hex: "EFEAE0") }
  static var beige700: Color { .init(hex: "DAD1BF") }
  static var beige800: Color { .init(hex: "CEC1A8") }
  static var beige900: Color { .init(hex: "B7A88B") }

  // MARK: - Primitive / Gray
  static var gray50: Color { .init(hex: "EBEBEB") }
  static var gray100: Color { .init(hex: "D7D7D7") }
  static var gray200: Color { .init(hex: "B0AFAE") }
  static var gray300: Color { .init(hex: "888786") }
  static var gray400: Color { .init(hex: "615F5D") }
  static var gray500: Color { .init(hex: "393735") }
  static var gray600: Color { .init(hex: "2B2A28") }
  static var gray700: Color { .init(hex: "222120") }
  static var gray800: Color { .init(hex: "1A1918") }
  static var gray900: Color { .init(hex: "131212") }

  // MARK: - Compat / Neutral (alias of Gray)
  static var neutral50: Color { .gray50 }
  static var neutral100: Color { .gray100 }
  static var neutral200: Color { .gray200 }
  static var neutral300: Color { .gray300 }
  static var neutral400: Color { .gray400 }
  static var neutral500: Color { .gray500 }
  static var neutral600: Color { .gray600 }
  static var neutral700: Color { .gray700 }
  static var neutral800: Color { .gray800 }
  static var neutral900: Color { .gray900 }

  // MARK: - Primitive / Status
  static var errorAlpha: Color { .init(hex: "C92D33", alpha: 0.4) }
  static var errorDefault: Color { .init(hex: "C92D33") }
  static var warningDefault: Color { .init(hex: "FFB400") }
  static var warningAlpha: Color { .init(hex: "FFB400", alpha: 0.4) }

  // MARK: - Semantic / Background
  static var bgBeige: Color { .beige200 }
  static var bgDefault: Color { .init(hex: "FAFAF9") }
  static var bgSubtle: Color { .init(hex: "F5F5F4") }
  static var bgSubtler: Color { .gray50 }

  // MARK: - Semantic / Text
  static var textBody: Color { .gray400 }
  static var textDefault: Color { .gray800 }
  static var textError: Color { .errorDefault }
  static var textInverse: Color { .beige50 }
  static var textMuted: Color { .gray300 }
  static var textPrimary: Color { .primary500 }
  static var textSecondary: Color { .secondary500 }
  static var textSubtle: Color { .gray700 }
  static var textSubtler: Color { .gray500 }

  // MARK: - Semantic / Border
  static var borderBeigeDefault: Color { .beige600 }
  static var borderBeigeDisabled: Color { .beige500 }
  static var borderBeigeFocus: Color { .beige700 }
  static var borderBeigeSelected: Color { .beige700 }
  static var borderErrorDefault: Color { .init(hex: "C92D33", alpha: 0.4) }
  static var borderGrayDefault: Color { .gray100 }
  static var borderGraySubtle: Color { .gray50 }
  static var borderPrimaryDefault: Color { .primary500 }
  static var borderSecondarySelected: Color { .secondary500 }
  static var borderWarningDefault: Color { .init(hex: "FFB400", alpha: 0.4) }

  // MARK: - Semantic / Surface
  static var surfaceBeigeDefault: Color { .beige50 }
  static var surfaceBeigeStrong: Color { .beige400 }
  static var surfaceBeigeSubtle: Color { .beige300 }
  static var surfacePrimaryDefault: Color { .primary500 }
  static var surfacePrimarySubtle: Color { .primary50 }

  // MARK: - Semantic / Action
  static var actionBeigeDefault: Color { .beige300 }
  static var actionBeigePressed: Color { .beige400 }
  static var actionBeigeStrong: Color { .beige600 }
  static var actionBeigeSubtle: Color { .beige50 }
  static var actionGrayDefault: Color { .gray700 }
  static var actionGrayPressed: Color { .gray900 }
  static var actionPrimaryDefault: Color { .primary500 }
  static var actionPrimaryDisabled: Color { .primary200 }
  static var actionPrimaryPressed: Color { .primary800 }
  static var actionPrimarySubtle: Color { .primary100 }
  static var actionSecondaryDefault: Color { .secondary50 }

  // MARK: - Semantic / Icon
  static var iconGrayDefault: Color { .gray900 }
  static var iconGrayInverse: Color { .beige50 }
  static var iconGraySubtle: Color { .gray300 }
  static var iconPrimaryDefault: Color { .primary500 }

  // MARK: - Component
  static var avatarBackround: Color { .beige600 }
  static var badgeCounterBackground: Color { .gray500 }
  static var badgeCounterTextActive: Color { .beige50 }
  static var badgeCounterTextDefault: Color { .gray300 }
  static var badgeFilledBackground: Color { .beige600 }
  static var badgeFilledText: Color { .primary500 }
  static var badgeOutlineBackground: Color { .beige50 }
  static var badgeOutlineBorder: Color { .primary100 }
  static var badgeOutlineText: Color { .primary500 }
  static var badgePrimaryBackground: Color { .primary500 }
  static var badgePrimaryText: Color { .beige50 }
  static var buttonIconBackgroundDefault: Color { .primary500 }
  static var buttonIconBackgroundDisabled: Color { .primary200 }
  static var buttonPrimaryBackgroundDefault: Color { .primary500 }
  static var buttonPrimaryBackgroundDisabled: Color { .primary200 }
  static var buttonPrimaryBackgroundPressed: Color { .primary800 }
  static var buttonPrimaryTextDefault: Color { .beige50 }
  static var buttonSecondaryBackgroundDefault: Color { .secondary50 }
  static var buttonSecondaryBackgroundPressed: Color { .beige600 }
  static var buttonSecondaryTextDefault: Color { .primary500 }
  static var cardBaseBackgroundBeige: Color { .beige400 }
  static var cardBaseBackgroundDefault: Color { .beige50 }
  static var cardBaseBorderDefault: Color { .beige600 }
  static var cardBaseBorderPrimary: Color { .primary500 }
  static var cardBaseBorderSelected: Color { .secondary500 }
  static var cardBaseTextBody: Color { .gray400 }
  static var cardBaseTextDecription: Color { .gray300 }
  static var cardBaseTextInverse: Color { .beige50 }
  static var cardBaseTextPrimary: Color { .primary500 }
  static var cardBaseTextSecondary: Color { .secondary500 }
  static var cardBaseTextTitle: Color { .gray500 }
  static var cardGrayBackgroundDefault: Color { .gray700 }
  static var cardGrayBackgroundPressed: Color { .gray900 }
  static var cardGrayBorderSelected: Color { .secondary500 }
  static var cardOpinionBackgroundDefault: Color { .beige300 }
  static var cardOpinionBackgroundPressed: Color { .beige400 }
  static var cardOpinionBorderDefault: Color { .beige600 }
  static var cardOpinionBorderPressed: Color { .secondary500 }
  static var checkboxBackgroundDefault: Color { .primary50 }
  static var checkboxBackgroundSelected: Color { .primary500 }
  static var checkboxBorderDefault: Color { .primary100 }
  static var checkboxBorderSelected: Color { .primary700 }
  static var chipBackgroundDefault: Color { .primary500 }
  static var chipBackgroundSelected: Color { .primary50 }
  static var chipBorderDefault: Color { .primary500 }
  static var chipTextDefault: Color { .beige50 }
  static var chipTextSelected: Color { .primary500 }
  static var inputTextareaBackgroundDefault: Color { .beige50 }
  static var inputTextareaBackgroundDisabled: Color { .beige600 }
  static var inputTextareaBorderError: Color { .init(hex: "C92D33", alpha: 0.4) }
  static var inputTextareaTextDefault: Color { .gray300 }
  static var inputTextareaTextError: Color { .errorDefault }
  static var inputTextareaTextFocus: Color { .gray500 }
  static var inputTextfieldBackgroundDefault: Color { .beige50 }
  static var inputTextfieldBackgroundDisabled: Color { .beige400 }
  static var inputTextfieldBorderDefault: Color { .beige600 }
  static var inputTextfieldBorderError: Color { .primary100 }
  static var inputTextfieldBorderFocus: Color { .beige700 }
  static var inputTextfieldTextDefault: Color { .gray300 }
  static var inputTextfieldTextError: Color { .errorDefault }
  static var inputTextfieldTextFocus: Color { .gray500 }
  static var listItemAgreementBackgroundDefault: Color { .bgDefault }
  static var listItemAgreementBorderDefault: Color { .gray50 }
  static var listItemAgreementBorderError: Color { .init(hex: "C92D33", alpha: 0.4) }
  static var listItemAgreementTextDefualt: Color { .gray800 }
  static var listItemAgreementTextError: Color { .errorDefault }
  static var navigationTabBorderActive: Color { .primary500 }
  static var navigationTabBorderDefault: Color { .gray100 }
  static var navigationTabTextActive: Color { .primary500 }
  static var navigationTabTextDefault: Color { .gray300 }
  static var popupBackground: Color { .beige400 }
  static var popupBorder: Color { .primary500 }
  static var popupText: Color { .gray800 }
  static var toggleThumbDefault: Color { .beige50 }
  static var toggleTrackOff: Color { .gray100 }
  static var toggleTrackOn: Color { .primary500 }
}
