//
//  WorkSpace.swift
//  Manifests
//
//  Created by 서원지 on 6/7/24.
//

import ProjectDescription
import ProjectTemplatePlugin

// 이름은 Project.Environment.appName 하나로만 정한다.
// PROJECT_NAME 환경변수 폴백은 이미 그 안에 있어서 여기서 또 분기하면 로직만 두 벌이 된다.
//
// Stage 스킴은 App 프로젝트의 appSchemes 가 이미 만든다. 워크스페이스에서 또 만들면
// 같은 이름이 두 번 생기므로 여기서는 커버리지 수집 범위만 정한다.
let workspace = Workspace(
  name: Project.Environment.appName,
  projects: [
    "Projects/**"
  ],
  generationOptions: .options(
    // 커버리지 대상은 스킴과 관련된 타깃으로 Tuist 가 좁힌다.
    // 모듈을 손으로 나열하면 추가·개명할 때마다 목록이 실제 타깃과 어긋난다.
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant)
  )
)
