// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json

import SwiftUI

public extension ShapeStyle where Self == Color {

  // MARK: - Brand / Primary
  static var primary50: Color { .init(hex: "F3EBE9") }
  static var primary100: Color { .init(hex: "E7D7D3") }
  static var primary200: Color { .init(hex: "D0AFA8") }
  static var primary300: Color { .init(hex: "B8887C") }
  static var primary400: Color { .init(hex: "A16051") }
  static var primary500: Color { .init(hex: "893825") }
  static var primary600: Color { .init(hex: "7A3626") }
  static var primary700: Color { .init(hex: "71372A") }
  static var primary800: Color { .init(hex: "653226") }
  static var primary900: Color { .init(hex: "4E2A21") }
  static var primaryAlpha8: Color { .init(hex: "893825", alpha: 0.08) }

  // MARK: - Brand / Secondary
  static var secondary50: Color { .init(hex: "FCF8F1") }
  static var secondary100: Color { .init(hex: "F9F1E3") }
  static var secondary200: Color { .init(hex: "F3E3C7") }
  static var secondary300: Color { .init(hex: "EDD5AC") }
  static var secondary400: Color { .init(hex: "E7C790") }
  static var secondary500: Color { .init(hex: "E1B974") }
  static var secondary600: Color { .init(hex: "CEA969") }
  static var secondary700: Color { .init(hex: "B7965C") }
  static var secondary800: Color { .init(hex: "A38653") }
  static var secondary900: Color { .init(hex: "92784A") }

  // MARK: - Brand / Beige
  static var beige50: Color { .init(hex: "FEFEFD") }
  static var beige100: Color { .init(hex: "FDFCFB") }
  static var beige200: Color { .init(hex: "FBF9F7") }
  static var beige300: Color { .init(hex: "F9F7F2") }
  static var beige400: Color { .init(hex: "F7F4EE") }
  static var beige500: Color { .init(hex: "F5F1EA") }
  static var beige600: Color { .init(hex: "EFEAE0") }
  static var beige700: Color { .init(hex: "DAD1BF") }
  static var beige800: Color { .init(hex: "CEC1A8") }
  static var beige900: Color { .init(hex: "B7A88B") }

  // MARK: - Brand / Neutral
  static var neutral50: Color { .init(hex: "EBEBEB") }
  static var neutral100: Color { .init(hex: "D7D7D7") }
  static var neutral200: Color { .init(hex: "B0AFAE") }
  static var neutral300: Color { .init(hex: "888786") }
  static var neutral400: Color { .init(hex: "615F5D") }
  static var neutral500: Color { .init(hex: "393735") }
  static var neutral600: Color { .init(hex: "2B2A28") }
  static var neutral700: Color { .init(hex: "222120") }
  static var neutral800: Color { .init(hex: "1A1918") }
  static var neutral900: Color { .init(hex: "131212") }

  // MARK: - Semantic / Text
  static var textBrand: Color { .primary500 }
  static var textInverse: Color { .init(hex: "FEFEFD") }
  static var textMuted: Color { .neutral300 }
  static var textPrimary: Color { .neutral900 }
  static var textSecondary: Color { .neutral700 }
  static var textTertiary: Color { .neutral500 }

  // MARK: - Semantic / Border
  static var borderDefault: Color { .beige600 }
  static var borderDisabled: Color { .beige500 }
  static var borderError: Color { .statusErrorAlpha }
  static var borderFocus: Color { .beige700 }
  static var borderSelected: Color { .secondary500 }
  static var borderStrong: Color { .primary500 }
  static var borderSubtle: Color { .beige700 }

  // MARK: - Semantic / Surface
  static var surfaceDefault: Color { .beige50 }
  static var surfaceDisabled: Color { .primary200 }
  static var surfaceSelected: Color { .primary500 }
  static var surfaceSubtle: Color { .beige300 }
  static var surfaceTertiary: Color { .beige400 }

  // MARK: - Semantic / Background
  static var bgBrand: Color { .beige200 }
  static var bgDefault: Color { .init(hex: "FAFAF9") }
  static var bgInverse: Color { .neutral800 }
  static var bgOverlay: Color { .init(hex: "000000", alpha: 0.4) }
  static var bgSubtle: Color { .init(hex: "F5F5F4") }
  static var bgTertiary: Color { .neutral50 }

  // MARK: - Semantic / Status
  static var statusErrorAlpha: Color { .init(hex: "C92D33", alpha: 0.4) }
  static var statusError: Color { .init(hex: "C92D33") }
  static var statusWarningAlpha: Color { .init(hex: "FFB400", alpha: 0.4) }
  static var statusWarning: Color { .init(hex: "FFB400") }
  // MARK: - Component
  static var bedgeFilledBackgroundDefault: Color { .beige600 }
  static var bedgeFilledBackgroundInverse: Color { .primary500 }
  static var bedgeFilledTextDefault: Color { .primary500 }
  static var bedgeFilledTextInverse: Color { .beige50 }
  static var bedgeOutlineBackround: Color { .beige50 }
  static var bedgeOutlineBorder: Color { .primary100 }
  static var bedgeOutlineText: Color { .primary500 }
  static var buttonPrimaryBackgroundDefault: Color { .primary500 }
  static var buttonPrimaryBackgroundDisabled: Color { .primary200 }
  static var buttonPrimaryBackgroundPressed: Color { .primary800 }
  static var buttonPrimaryTextDefault: Color { .beige50 }
  static var buttonSecondaryBackgroundDefault: Color { .beige300 }
  static var buttonSecondaryBackgroundPressed: Color { .beige400 }
  static var buttonSecondaryBorderDefault: Color { .beige600 }
  static var buttonSecondaryBorderPressed: Color { .secondary500 }
  static var buttonSecondaryTextDefault: Color { .neutral600 }
  static var buttonSecondaryTextDisabled: Color { .neutral300 }
  static var inputBorderActive: Color { .beige700 }
  static var inputBorderDefault: Color { .beige600 }
  static var inputBorderError: Color { .borderError }
  static var inputSurfaceDefault: Color { .beige50 }
  static var inputSurfaceDisabled: Color { .beige300 }
  static var inputTextActive: Color { .neutral500 }
  static var inputTextDefault: Color { .neutral300 }
  static var inputTextError: Color { .statusError }

}
