// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/{primitive,semantic,component}.json

import SwiftUI

public enum ComponentToken {
  public enum Avatar {
    public static var backround: Color { .avatarBackround }
  }

  public enum Badge {
    public enum Counter {
      public static var background: Color { .badgeCounterBackground }

      public enum Text {
        public static var active: Color { .badgeCounterTextActive }
        public static var `default`: Color { .badgeCounterTextDefault }
      }
    }

    public enum Filled {
      public static var background: Color { .badgeFilledBackground }
      public static var text: Color { .badgeFilledText }
    }

    public enum Outline {
      public static var background: Color { .badgeOutlineBackground }
      public static var border: Color { .badgeOutlineBorder }
      public static var text: Color { .badgeOutlineText }
    }

    public enum Primary {
      public static var background: Color { .badgePrimaryBackground }
      public static var text: Color { .badgePrimaryText }
    }
  }

  public enum Button {
    public enum Icon {
      public static var size: CGFloat { .buttonIconSize }

      public enum Background {
        public static var `default`: Color { .buttonIconBackgroundDefault }
        public static var disabled: Color { .buttonIconBackgroundDisabled }
      }
    }

    public enum Primary {
      public enum Background {
        public static var `default`: Color { .buttonPrimaryBackgroundDefault }
        public static var disabled: Color { .buttonPrimaryBackgroundDisabled }
        public static var pressed: Color { .buttonPrimaryBackgroundPressed }
      }

      public enum Large {
        public static var height: CGFloat { .buttonPrimaryLargeHeight }
        public static var width: CGFloat { .buttonPrimaryLargeWidth }
      }

      public enum Medium {
        public static var height: CGFloat { .buttonPrimaryMediumHeight }
        public static var width: CGFloat { .buttonPrimaryMediumWidth }
      }

      public enum Small {
        public static var height: CGFloat { .buttonPrimarySmallHeight }
        public static var width: CGFloat { .buttonPrimarySmallWidth }
      }

      public enum Text {
        public static var `default`: Color { .buttonPrimaryTextDefault }
      }
    }

    public enum Secondary {
      public enum Background {
        public static var `default`: Color { .buttonSecondaryBackgroundDefault }
        public static var pressed: Color { .buttonSecondaryBackgroundPressed }
      }

      public enum Text {
        public static var `default`: Color { .buttonSecondaryTextDefault }
      }
    }
  }

  public enum Card {
    public enum Avatar {
      public static var lg: CGFloat { .cardAvatarLg }
      public static var md: CGFloat { .cardAvatarMd }
      public static var sm: CGFloat { .cardAvatarSm }
    }

    public enum Base {
      public enum Background {
        public static var beige: Color { .cardBaseBackgroundBeige }
        public static var `default`: Color { .cardBaseBackgroundDefault }
      }

      public enum Border {
        public static var `default`: Color { .cardBaseBorderDefault }
        public static var primary: Color { .cardBaseBorderPrimary }
        public static var selected: Color { .cardBaseBorderSelected }
      }

      public enum Text {
        public static var body: Color { .cardBaseTextBody }
        public static var decription: Color { .cardBaseTextDecription }
        public static var inverse: Color { .cardBaseTextInverse }
        public static var primary: Color { .cardBaseTextPrimary }
        public static var secondary: Color { .cardBaseTextSecondary }
        public static var title: Color { .cardBaseTextTitle }
      }
    }

    public enum Gray {
      public enum Background {
        public static var `default`: Color { .cardGrayBackgroundDefault }
        public static var pressed: Color { .cardGrayBackgroundPressed }
      }

      public enum Border {
        public static var selected: Color { .cardGrayBorderSelected }
      }
    }

    public enum Opinion {
      public enum Background {
        public static var `default`: Color { .cardOpinionBackgroundDefault }
        public static var pressed: Color { .cardOpinionBackgroundPressed }
      }

      public enum Border {
        public static var `default`: Color { .cardOpinionBorderDefault }
        public static var pressed: Color { .cardOpinionBorderPressed }
      }
    }
  }

  public enum Checkbox {
    public static var height: CGFloat { .checkboxHeight }
    public static var width: CGFloat { .checkboxWidth }

    public enum Background {
      public static var `default`: Color { .checkboxBackgroundDefault }
      public static var selected: Color { .checkboxBackgroundSelected }
    }

    public enum Border {
      public static var `default`: Color { .checkboxBorderDefault }
      public static var selected: Color { .checkboxBorderSelected }
    }
  }

  public enum Chip {
    public enum Background {
      public static var `default`: Color { .chipBackgroundDefault }
      public static var selected: Color { .chipBackgroundSelected }
    }

    public enum Border {
      public static var `default`: Color { .chipBorderDefault }
    }

    public enum Text {
      public static var `default`: Color { .chipTextDefault }
      public static var selected: Color { .chipTextSelected }
    }
  }

  public enum Input {
    public enum Textarea {
      public enum Background {
        public static var `default`: Color { .inputTextareaBackgroundDefault }
        public static var disabled: Color { .inputTextareaBackgroundDisabled }
      }

      public enum Border {
        public static var error: Color { .inputTextareaBorderError }
      }

      public enum Text {
        public static var `default`: Color { .inputTextareaTextDefault }
        public static var error: Color { .inputTextareaTextError }
        public static var focus: Color { .inputTextareaTextFocus }
      }
    }

    public enum Textfield {
      public static var height: CGFloat { .inputTextfieldHeight }
      public static var width: CGFloat { .inputTextfieldWidth }

      public enum Background {
        public static var `default`: Color { .inputTextfieldBackgroundDefault }
        public static var disabled: Color { .inputTextfieldBackgroundDisabled }
      }

      public enum Border {
        public static var `default`: Color { .inputTextfieldBorderDefault }
        public static var error: Color { .inputTextfieldBorderError }
        public static var focus: Color { .inputTextfieldBorderFocus }
      }

      public enum Text {
        public static var `default`: Color { .inputTextfieldTextDefault }
        public static var error: Color { .inputTextfieldTextError }
        public static var focus: Color { .inputTextfieldTextFocus }
      }
    }
  }

  public enum ListItem {
    public enum Agreement {
      public enum Background {
        public static var `default`: Color { .listItemAgreementBackgroundDefault }
      }

      public enum Border {
        public static var `default`: Color { .listItemAgreementBorderDefault }
        public static var error: Color { .listItemAgreementBorderError }
      }

      public enum Text {
        public static var defualt: Color { .listItemAgreementTextDefualt }
        public static var error: Color { .listItemAgreementTextError }
      }
    }
  }

  public enum Navigation {
    public enum Tab {
      public enum Border {
        public static var active: Color { .navigationTabBorderActive }
        public static var `default`: Color { .navigationTabBorderDefault }
      }

      public enum Text {
        public static var active: Color { .navigationTabTextActive }
        public static var `default`: Color { .navigationTabTextDefault }
      }
    }
  }

  public enum Padding {
    public enum Appbar {
      public static var horizontal: CGFloat { .paddingAppbarHorizontal }
      public static var vertical: CGFloat { .paddingAppbarVertical }
    }

    public enum Badge {
      public static var horizontal: CGFloat { .paddingBadgeHorizontal }
      public static var vertical: CGFloat { .paddingBadgeVertical }
    }

    public enum Button {
      public enum Primary {
        public enum Large {
          public static var horizontal: CGFloat { .paddingButtonPrimaryLargeHorizontal }
          public static var vertical: CGFloat { .paddingButtonPrimaryLargeVertical }
        }

        public enum Medium {
          public static var horizontal: CGFloat { .paddingButtonPrimaryMediumHorizontal }
          public static var vertical: CGFloat { .paddingButtonPrimaryMediumVertical }
        }

        public enum Small {
          public static var horizontal: CGFloat { .paddingButtonPrimarySmallHorizontal }
          public static var vertical: CGFloat { .paddingButtonPrimarySmallVertical }
        }
      }
    }

    public enum Card {
      public static var base: CGFloat { .paddingCardBase }
    }

    public enum Chip {
      public static var horizontal: CGFloat { .paddingChipHorizontal }
      public static var vertical: CGFloat { .paddingChipVertical }
    }

    public enum Input {
      public static var horizontal: CGFloat { .paddingInputHorizontal }
    }

    public enum Navigation {
      public enum Tab {
        public static var horizontal: CGFloat { .paddingNavigationTabHorizontal }
        public static var vertical: CGFloat { .paddingNavigationTabVertical }
      }
    }
  }

  public enum Popup {
    public static var background: Color { .popupBackground }
    public static var border: Color { .popupBorder }
    public static var text: Color { .popupText }
    public static var width: CGFloat { .popupWidth }
  }

  public enum Thumbnail {
    public static var height: CGFloat { .thumbnailHeight }
    public static var width: CGFloat { .thumbnailWidth }
  }

  public enum Toggle {
    public static var height: CGFloat { .toggleHeight }
    public static var width: CGFloat { .toggleWidth }

    public enum Thumb {
      public static var `default`: Color { .toggleThumbDefault }
      public static var size: CGFloat { .toggleThumbSize }
    }

    public enum Track {
      public static var off: Color { .toggleTrackOff }
      public static var on: Color { .toggleTrackOn }
    }
  }
}
