// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json

import SwiftUI

public enum ComponentToken {
  public enum Bedge {
    public enum Filled {
      public enum Background {
        public static var `default`: Color { .bedgeFilledBackgroundDefault }
        public static var inverse: Color { .bedgeFilledBackgroundInverse }
      }

      public enum Text {
        public static var `default`: Color { .bedgeFilledTextDefault }
        public static var inverse: Color { .bedgeFilledTextInverse }
      }
    }

    public enum Outline {
      public static var backround: Color { .bedgeOutlineBackround }
      public static var border: Color { .bedgeOutlineBorder }
      public static var text: Color { .bedgeOutlineText }
    }
  }

  public enum Button {
    public static var radius: CGFloat { .buttonRadius }

    public enum Primary {
      public enum Background {
        public static var `default`: Color { .buttonPrimaryBackgroundDefault }
        public static var disabled: Color { .buttonPrimaryBackgroundDisabled }
        public static var pressed: Color { .buttonPrimaryBackgroundPressed }
      }

      public enum Text {
        public static var `default`: Color { .buttonPrimaryTextDefault }
      }
    }

    public enum Secondary {
      public enum Background {
        public static var `default`: Color { .buttonSecondaryBackgroundDefault }
        public static var pressed: Color { .buttonSecondaryBackgroundPressed }
      }

      public enum Border {
        public static var `default`: Color { .buttonSecondaryBorderDefault }
        public static var pressed: Color { .buttonSecondaryBorderPressed }
      }

      public enum Text {
        public static var `default`: Color { .buttonSecondaryTextDefault }
        public static var disabled: Color { .buttonSecondaryTextDisabled }
      }
    }
  }

  public enum Input {
    public enum Border {
      public static var active: Color { .inputBorderActive }
      public static var `default`: Color { .inputBorderDefault }
      public static var error: Color { .inputBorderError }
    }

    public enum Surface {
      public static var `default`: Color { .inputSurfaceDefault }
      public static var disabled: Color { .inputSurfaceDisabled }
    }

    public enum Text {
      public static var active: Color { .inputTextActive }
      public static var `default`: Color { .inputTextDefault }
      public static var error: Color { .inputTextError }
    }
  }
}
