// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json

import SwiftUI

public enum ComponentToken {
  public enum Bedge {
    public enum Filled {
      public enum Background {
        public static var `default`: Color { .beige600 }
        public static var inverse: Color { .primary500 }
      }

      public enum Text {
        public static var `default`: Color { .primary500 }
        public static var inverse: Color { .beige50 }
      }
    }

    public enum Outline {
      public static var backround: Color { .beige50 }
      public static var border: Color { .primary100 }
      public static var text: Color { .primary500 }
    }
  }

  public enum Button {
    public static var radius: CGFloat { .`default` }

    public enum Primary {
      public enum Background {
        public static var `default`: Color { .primary500 }
        public static var disabled: Color { .primary200 }
        public static var pressed: Color { .primary800 }
      }

      public enum Text {
        public static var `default`: Color { .beige50 }
      }
    }

    public enum Secondary {
      public enum Background {
        public static var `default`: Color { .beige300 }
        public static var pressed: Color { .beige400 }
      }

      public enum Border {
        public static var `default`: Color { .beige600 }
        public static var pressed: Color { .secondary500 }
      }

      public enum Text {
        public static var `default`: Color { .neutral600 }
        public static var disabled: Color { .neutral300 }
      }
    }
  }

  public enum Input {
    public enum Border {
      public static var active: Color { .beige700 }
      public static var `default`: Color { .beige600 }
      public static var error: Color { .borderError }
    }

    public enum Surface {
      public static var `default`: Color { .beige50 }
      public static var disabled: Color { .beige300 }
    }

    public enum Text {
      public static var active: Color { .neutral500 }
      public static var `default`: Color { .neutral300 }
      public static var error: Color { .statusError }
    }
  }
}
