// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json

import CoreGraphics

public extension CGFloat {

  // MARK: - Component
  static let buttonRadius: CGFloat = .`default`
}
