// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json

import CoreGraphics

public extension CGFloat {

  // MARK: - Radius
  static let none: CGFloat = 0
  static let `default`: CGFloat = 2
  static let full: CGFloat = 999
}
