// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/{primitive,semantic,component}.json

import CoreGraphics

public extension CGFloat {

  // MARK: - Radius
  static let radiusDefault: CGFloat = 2
  static let radiusMax: CGFloat = 999
}
