// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: SWYP-Find/design-tokens repo (primitive.json / semantic.json / component.json)

import CoreGraphics

public extension CGFloat {

  // MARK: - Primitive Spacing
  static let s0: CGFloat = 0
  static let s2: CGFloat = 2
  static let s4: CGFloat = 4
  static let s6: CGFloat = 6
  static let s8: CGFloat = 8
  static let s12: CGFloat = 12
  static let s16: CGFloat = 16
  static let s20: CGFloat = 20
  static let s24: CGFloat = 24
  static let s32: CGFloat = 32
  static let s40: CGFloat = 40
  static let s48: CGFloat = 48
  static let s64: CGFloat = 64
  static let s80: CGFloat = 80
  static let s96: CGFloat = 96

  // MARK: - Primitive Sizing
  static let iconLg: CGFloat = 24
  static let iconMd: CGFloat = 20
  static let iconSm: CGFloat = 16
  static let iconXs: CGFloat = 12
  static let avatarLg: CGFloat = 68
  static let avatarMd: CGFloat = 40
  static let avatarSm: CGFloat = 36
  static let controlMd: CGFloat = 52
  static let controlSm: CGFloat = 28

  // MARK: - Semantic Gap
  static let gap0: CGFloat = 0
  static let gap2: CGFloat = 2
  static let gap4: CGFloat = 4
  static let gap6: CGFloat = 6
  static let gap8: CGFloat = 8
  static let gap12: CGFloat = 12
  static let gap16: CGFloat = 16
  static let gap20: CGFloat = 20
  static let gap24: CGFloat = 24
  static let gap32: CGFloat = 32
  static let gap40: CGFloat = 40

  // MARK: - Semantic Padding
  static let paddingComponent12: CGFloat = 12
  static let paddingComponent16: CGFloat = 16
  static let paddingComponent2: CGFloat = 2
  static let paddingComponent4: CGFloat = 4
  static let paddingComponent6: CGFloat = 6
  static let paddingComponent8: CGFloat = 8
  static let paddingContainer12: CGFloat = 12
  static let paddingContainer16: CGFloat = 16
  static let paddingContainer20: CGFloat = 20
  static let paddingContainer24: CGFloat = 24
  static let paddingContainer32: CGFloat = 32
  static let paddingContainer40: CGFloat = 40
  static let paddingContainer8: CGFloat = 8
  static let paddingScreenHorizontal: CGFloat = 16

  // MARK: - Semantic Border Width
  static let borderWidthRegular: CGFloat = 1
  static let borderWidthMedium: CGFloat = 1.5
  static let borderWidthLarge: CGFloat = 4
}
