// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/{primitive,semantic,component}.json

import CoreGraphics

public extension CGFloat {

  // MARK: - Component
  static let buttonIconSize: CGFloat = 36
  static let buttonPrimaryLargeHeight: CGFloat = 52
  static let buttonPrimaryLargeWidth: CGFloat = 343
  static let buttonPrimaryMediumHeight: CGFloat = 42
  static let buttonPrimaryMediumWidth: CGFloat = 343
  static let buttonPrimarySmallHeight: CGFloat = 42
  static let buttonPrimarySmallWidth: CGFloat = 100
  static let cardAvatarLg: CGFloat = 68
  static let cardAvatarMd: CGFloat = 40
  static let cardAvatarSm: CGFloat = 36
  static let checkboxHeight: CGFloat = 24
  static let checkboxWidth: CGFloat = 24
  static let inputTextfieldHeight: CGFloat = 44
  static let inputTextfieldWidth: CGFloat = 343
  static let paddingAppbarHorizontal: CGFloat = 16
  static let paddingAppbarVertical: CGFloat = 12
  static let paddingBadgeHorizontal: CGFloat = 6
  static let paddingBadgeVertical: CGFloat = 2
  static let paddingButtonPrimaryLargeHorizontal: CGFloat = 12
  static let paddingButtonPrimaryLargeVertical: CGFloat = 12
  static let paddingButtonPrimaryMediumHorizontal: CGFloat = 12
  static let paddingButtonPrimaryMediumVertical: CGFloat = 12
  static let paddingButtonPrimarySmallHorizontal: CGFloat = 12
  static let paddingButtonPrimarySmallVertical: CGFloat = 12
  static let paddingCardBase: CGFloat = 16
  static let paddingChipHorizontal: CGFloat = 12
  static let paddingChipVertical: CGFloat = 6
  static let paddingInputHorizontal: CGFloat = 8
  static let paddingNavigationTabHorizontal: CGFloat = 12
  static let paddingNavigationTabVertical: CGFloat = 12
  static let popupWidth: CGFloat = 393
  static let thumbnailHeight: CGFloat = 140
  static let thumbnailWidth: CGFloat = 196
  static let toggleHeight: CGFloat = 18
  static let toggleThumbSize: CGFloat = 14
  static let toggleWidth: CGFloat = 32
}
