// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json

import CoreGraphics

public extension CGFloat {

  // MARK: - Spacing
  static let s0: CGFloat = 0
  static let s2: CGFloat = 2
  static let s4: CGFloat = 4
  static let s8: CGFloat = 8
  static let s16: CGFloat = 16
  static let s24: CGFloat = 24
  static let s32: CGFloat = 32
  static let s40: CGFloat = 40
  static let s48: CGFloat = 48
  static let s64: CGFloat = 64
  static let s80: CGFloat = 80
  static let s96: CGFloat = 96
}
