#!/usr/bin/env swift
//
//  TokenGenerator.swift
//  Reads Mode 1.tokens.json and emits Swift token files.
//  Run from repo root:  swift Tools/TokenGenerator.swift
//

import Foundation

// MARK: - Paths

let cwd = FileManager.default.currentDirectoryPath
let jsonURL = URL(fileURLWithPath: "\(cwd)/Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json")
let sourcesDir = "\(cwd)/Projects/Shared/DesignSystem/Sources"
let colorOut = "\(sourcesDir)/Color/ShapeStyle+.swift"
let cgfloatDir = "\(sourcesDir)/Extension/CGFloat"
let radiusOut = "\(cgfloatDir)/CGFloat+Radius+.swift"
let spacingOut = "\(cgfloatDir)/CGFloat+Spacing+.swift"
try? FileManager.default.createDirectory(atPath: cgfloatDir, withIntermediateDirectories: true)

let data: Data
do {
  data = try Data(contentsOf: jsonURL)
} catch {
  fputs("[token-gen] cannot read JSON: \(jsonURL.path)\n", stderr)
  exit(1)
}

guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
  fputs("[token-gen] invalid JSON root\n", stderr); exit(1)
}

// MARK: - Helpers

func valueOf(_ any: Any) -> Any? {
  (any as? [String: Any])?["$value"]
}

func hexAlpha(_ value: Any) -> (hex: String, alpha: Double)? {
  guard let d = value as? [String: Any], let hex = d["hex"] as? String else { return nil }
  let raw = hex.hasPrefix("#") ? String(hex.dropFirst()) : hex
  let a = (d["alpha"] as? Double) ?? 1.0
  return (raw.uppercased(), a)
}

func aliasToSwiftName(_ alias: String) -> String? {
  var s = alias
  if s.hasPrefix("{"), s.hasSuffix("}") { s = String(s.dropFirst().dropLast()) }
  let p = s.split(separator: ".").map(String.init)
  if p.count >= 4, p[0] == "Colors", p[1] == "brand" {
    if p.count == 5, p[3] == "Alpha" { return "\(p[2])Alpha\(p[4])" }
    return "\(p[2])\(p[3])"
  }
  if p.count >= 5, p[0] == "Colors", p[1] == "semantic", p[2] == "status" {
    let bucket = p[3].prefix(1).uppercased() + p[3].dropFirst()
    let leaf = p[4]
    return leaf == "Alpha" ? "status\(bucket)Alpha" : "status\(bucket)"
  }
  return nil
}

func capitalizeFirst(_ s: String) -> String {
  s.prefix(1).uppercased() + s.dropFirst()
}

func formatNumber(_ d: Double) -> String {
  if d == d.rounded() { return "\(Int(d))" }
  let rounded = (d * 100).rounded() / 100
  return rounded == d.rounded() ? "\(Int(d))" : String(format: "%g", rounded)
}

func colorBody(hex: String, alpha: Double) -> String {
  alpha < 1 ? ".init(hex: \"\(hex)\", alpha: \(formatNumber(alpha)))" : ".init(hex: \"\(hex)\")"
}

func writeFile(_ path: String, _ contents: String) throws {
  try contents.write(toFile: path, atomically: true, encoding: .utf8)
  print("[token-gen] wrote \(path)")
}

let header = """
// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: Projects/Shared/DesignSystem/Resources/Mode 1.tokens.json
"""

// MARK: - Colors

let colors = json["Colors"] as! [String: Any]
let brand = colors["brand"] as! [String: Any]
let semantic = colors["semantic"] as! [String: Any]
let scales = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"]
let brandGroups = ["primary", "secondary", "beige", "neutral"]

var lines: [String] = [header, "", "import SwiftUI", "", "public extension ShapeStyle where Self == Color {", ""]

// brand
for group in brandGroups {
  guard let g = brand[group] as? [String: Any] else { continue }
  lines.append("  // MARK: - Brand / \(capitalizeFirst(group))")
  for s in scales {
    if let node = g[s] as? [String: Any], let v = valueOf(node), let h = hexAlpha(v) {
      lines.append("  static var \(group)\(s): Color { \(colorBody(hex: h.hex, alpha: h.alpha)) }")
    }
  }
  if let alpha = g["Alpha"] as? [String: Any] {
    for (k, v) in alpha.sorted(by: { $0.key < $1.key }) {
      if let node = v as? [String: Any], let val = valueOf(node), let h = hexAlpha(val) {
        lines.append("  static var \(group)Alpha\(k): Color { \(colorBody(hex: h.hex, alpha: h.alpha)) }")
      }
    }
  }
  lines.append("")
}

// semantic prefixed groups
let semGroups: [(jsonKey: String, swiftPrefix: String)] = [
  ("text", "text"),
  ("border", "border"),
  ("surface", "surface"),
  ("background", "bg"),
]
for (key, prefix) in semGroups {
  guard let group = semantic[key] as? [String: Any] else { continue }
  lines.append("  // MARK: - Semantic / \(capitalizeFirst(key))")
  for (rawName, val) in group.sorted(by: { $0.key < $1.key }) {
    guard let node = val as? [String: Any], let v = valueOf(node) else { continue }
    let name = "\(prefix)\(capitalizeFirst(rawName))"
    if let h = hexAlpha(v) {
      lines.append("  static var \(name): Color { \(colorBody(hex: h.hex, alpha: h.alpha)) }")
    } else if let aliasStr = v as? String, let target = aliasToSwiftName(aliasStr) {
      lines.append("  static var \(name): Color { .\(target) }")
    }
  }
  lines.append("")
}

// status nested (status.error.error / status.error.Alpha / status.warning.warning / status.warning.Alpha)
if let status = semantic["status"] as? [String: Any] {
  lines.append("  // MARK: - Semantic / Status")
  for bucket in ["error", "warning"] {
    guard let b = status[bucket] as? [String: Any] else { continue }
    for (k, v) in b.sorted(by: { $0.key < $1.key }) {
      guard let node = v as? [String: Any], let val = valueOf(node), let h = hexAlpha(val) else { continue }
      let bucketCap = capitalizeFirst(bucket)
      let name = (k == "Alpha") ? "status\(bucketCap)Alpha" : "status\(bucketCap)"
      lines.append("  static var \(name): Color { \(colorBody(hex: h.hex, alpha: h.alpha)) }")
    }
  }
}

lines.append("}")
lines.append("")
try writeFile(colorOut, lines.joined(separator: "\n"))

// MARK: - Radius

let radius = json["Radius"] as! [String: Any]
let radiusOrder = ["none", "default", "full"]
var rLines: [String] = [header, "", "import CoreGraphics", "", "public extension CGFloat {", ""]
rLines.append("  // MARK: - Radius")
for k in radiusOrder {
  guard let node = radius[k] as? [String: Any], let v = valueOf(node), let n = v as? Double else { continue }
  let safe = (k == "default") ? "`default`" : k
  rLines.append("  static let \(safe): CGFloat = \(formatNumber(n))")
}

rLines.append("}")
rLines.append("")
try writeFile(radiusOut, rLines.joined(separator: "\n"))

// MARK: - Spacing

let spacing = json["Spacing"] as! [String: Any]
let spacingKeys = spacing.keys.compactMap(Int.init).sorted()
var sLines: [String] = [header, "", "import CoreGraphics", "", "public extension CGFloat {", ""]
sLines.append("  // MARK: - Spacing")
for k in spacingKeys {
  guard let node = spacing[String(k)] as? [String: Any], let v = valueOf(node), let n = v as? Double else { continue }
  sLines.append("  static let s\(k): CGFloat = \(formatNumber(n))")
}

sLines.append("}")
sLines.append("")
try writeFile(spacingOut, sLines.joined(separator: "\n"))

print("[token-gen] done.")
