// AUTO-GENERATED by Tools/TokenGenerator.swift — DO NOT EDIT
// Source: SWYP-Find/design-tokens repo (primitive.json / semantic.json / component.json)

import CoreGraphics

public extension CGFloat {

  // MARK: - Radius
  static let radiusDefault: CGFloat = 2
  static let radiusMax: CGFloat = 999
}
